### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by lbazan** [jonathf/numpoly#39]
test/test_align.py .                                                     [  0%]
test/test_array_function.py ............................................ [ 35%]
.......................................................................  [ 90%]
test/test_baseclass.py F                                                 [ 91%]
test/test_construct.py ..                                                [ 92%]
test/test_poly_function.py .........                                     [100%]
=================================== FAILURES ===================================
_________________________________ test_scalars _________________________________
    def test_scalars():
        assert XY.shape == (2,)
        assert XY.size == 2
        assert X.shape == ()
        assert X.size == 1
        assert EMPTY.shape in [(), (0,)]  # different behavior in py2/3
        assert EMPTY.size == 0
    
        assert numpy.all(numpy.array(XY.coefficients) == [[1, 0], [0, 1]])
        assert X.coefficients == [1]
        assert EMPTY.coefficients == []
    
        assert numpy.all(XY.exponents == [[1, 0], [0, 1]])
        assert XY.exponents.shape == (2, 2)
        assert X.exponents == 1
        assert X.exponents.shape == (1, 1)
        assert numpy.all(EMPTY.exponents == 0)
        assert EMPTY.exponents.shape == (1, 1)
    
        assert numpy.all(XY.indeterminants == XY)
        assert X.indeterminants == X
    
        assert numpy.all(XY.values == numpy.array(
            [(1, 0), (0, 1)], dtype=[("<;", "<i8",), (";<", "<i8",)]))
        assert X.values == numpy.array((1,), dtype=[("<", "<i8",)])
>       assert EMPTY.values.dtype == numpy.dtype([(";", "<i8")])
E       AssertionError: assert dtype([(';', '<i4')]) == dtype([(';', '<i8')])
E        +  where dtype([(';', '<i4')]) = array([], dtype=[(';', '<i4')]).dtype
E        +    where array([], dtype=[(';', '<i4')]) = EMPTY.values
E        +  and   dtype([(';', '<i8')]) = <class 'numpy.dtype'>([(';', '<i8')])
E        +    where <class 'numpy.dtype'> = numpy.dtype
test/test_baseclass.py:33: AssertionError
=============================== warnings summary ===============================
test/test_array_function.py::test_numpy_isfinite[func_interface0]
test/test_array_function.py::test_numpy_isfinite[func_interface1]
  /builddir/build/BUILD/numpoly-0.1.16/test/test_array_function.py:236: RuntimeWarning: invalid value encountered in log
    poly = numpoly.polynomial([numpy.log(-1.), X, numpy.log(0)])
test/test_array_function.py::test_numpy_isfinite[func_interface0]
test/test_array_function.py::test_numpy_isfinite[func_interface1]
  /builddir/build/BUILD/numpoly-0.1.16/test/test_array_function.py:236: RuntimeWarning: divide by zero encountered in log
    poly = numpoly.polynomial([numpy.log(-1.), X, numpy.log(0)])
test/test_array_function.py::test_numpy_nonzero[interface0]
test/test_array_function.py::test_numpy_nonzero[interface1]
  /usr/lib/python3.8/site-packages/numpy/core/fromnumeric.py:61: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
    return bound(*args, **kwds)
test/test_array_function.py::test_numpy_nonzero[interface2]
  /builddir/build/BUILD/numpoly-0.1.16/conftest.py:17: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(arr).nonzero()` if the old behavior was intended.
    return func(*args, **kwargs)
test/test_poly_function.py::test_numpoly_cross_truncate
  /builddir/build/BUILD/numpoly-0.1.16/numpoly/poly_function/monomial/cross_truncation.py:49: RuntimeWarning: divide by zero encountered in true_divide
    out = numpy.sum((indices/bound)**norm, axis=-1)**(1./norm) <= 1
test/test_poly_function.py::test_numpoly_cross_truncate
  /builddir/build/BUILD/numpoly-0.1.16/numpoly/poly_function/monomial/cross_truncation.py:49: RuntimeWarning: invalid value encountered in true_divide
    out = numpy.sum((indices/bound)**norm, axis=-1)**(1./norm) <= 1
test/test_poly_function.py::test_numpoly_cross_truncate
  /builddir/build/BUILD/numpoly-0.1.16/numpoly/poly_function/monomial/cross_truncation.py:49: RuntimeWarning: invalid value encountered in less_equal
    out = numpy.sum((indices/bound)**norm, axis=-1)**(1./norm) <= 1
test/test_poly_function.py::test_numpoly_cross_truncate
  /builddir/build/BUILD/numpoly-0.1.16/numpoly/poly_function/monomial/cross_truncation.py:47: RuntimeWarning: divide by zero encountered in true_divide
    out = numpy.max(indices/bound, axis=-1) <= 1
test/test_poly_function.py::test_numpoly_cross_truncate
  /builddir/build/BUILD/numpoly-0.1.16/numpoly/poly_function/monomial/cross_truncation.py:47: RuntimeWarning: invalid value encountered in true_divide
    out = numpy.max(indices/bound, axis=-1) <= 1
test/test_poly_function.py::test_numpoly_cross_truncate
  /builddir/build/BUILD/numpoly-0.1.16/numpoly/poly_function/monomial/cross_truncation.py:47: RuntimeWarning: invalid value encountered in less_equal
    out = numpy.max(indices/bound, axis=-1) <= 1
-- Docs: https://docs.pytest.org/en/latest/warnings.html
============== 1 failed, 127 passed, 13 warnings in 15.83 seconds ==============

**Comment by jonathf** [comment]
Try again now.

**Comment by jonathf** [comment]
I consider the issue as solve. Reopen if that is not the case.
