### ISSUE TITLE
Preserving indeterminants with numpoly.multiply etc

### ISSUE THREAD

**Issue by mkgkruse** [jonathf/numpoly#75]
Is there a way to preserve the indeterminants of a set of polynomials when one applies multiply, sum, etc? For example, I create a set of 3-dimensional polynomials which may contain indeterminants q0, q1, q2 but sometimes only q0 (like when you create a basis of graded lexicographic monomials in d-dimensions). After applying align_indeterminants() I now have a set where all polynomials return ('q0, 'q1', 'q2') as "names" even though a polynomial may only be 'q0^2' etc. However, when I use numpoly.multiply(q0^2, q1) I get a new polynomial that has as names ('q0', 'q1') only. I would like to preserve the structure I had before where the new polynomial still returns ('q0, 'q1', 'q2') as "names" even though indeterminate 'q2' does not appear in the polynomial. This is useful because I have a dictionary that has as keys the exponents in the form [., ., .].

**Comment by jonathf** [comment]
Yes, that would be a neat feature.

Adding the feature in itself is not to dificult. I've added the feature as an option in version 1.1.1 now. Just update and add a global config line at the top of your script like this:
```python
numpoly.set_options(retain_names=True)
```
Let me know if it works for you.

I might let that even be default if it makes sense. But I'll need to do a lot more testing before I am comfortable doing so.

**Comment by jonathf** [comment]
(Implemented in #76)

**Comment by mkgkruse** [comment]
> Yes, that would be a neat feature.
> 
> Adding the feature in itself is not to dificult. I've added the feature as an option in version 1.1.1 now. Just update and add a global config line at the top of your script like this:
> 
> ```python
> numpoly.set_options(retain_names=True)
> ```
> 
> Let me know if it works for you.
> 
> I might let that even be default if it makes sense. But I'll need to do a lot more testing before I am comfortable doing so.

Thanks Jonathan! This did actually solve my problem. I think many users may want to keep this option because it makes evaluating polynomials on a structured grid very easy (as opposed to checking which indeterminants are present and then selecting the subset of points that match). 

I only got back to this work late last week after about a 2 month break.
