### ISSUE TITLE
Problem with cross_truncate

### ISSUE THREAD

**Issue by JeremyDubut** [jonathf/numpoly#80]
I found a problem with cross_truncation. A concrete case is:
`cross_truncate(numpy.array([[5,1,1,1,1]]), 10, 1.0)`
We are expecting the answer to be true (the sum is 9 which is below 9), but the answer is False. I think this is due to numerical errors, and maybe the definition of the norm should be reformulated (to avoid divisions)?

**Comment by jonathf** [comment]
I am not able to replicate. Do you mind posting stats about your setup. In pariticular, the version of your:
* OS/distro
* python
* numpy
* numpoly

**Comment by JeremyDubut** [comment]
Sorry, I am not used to this 😅
Here is my setup:
- MacOS BigSur 11.3.1
- python 3.8.6
- numpy 1.20.0
- numpoly 1.1.1

**Comment by jonathf** [comment]
Okay, the problem wasn't the version, but your code snippet. Replacing the 10 with a 9, and I also got the but:
```python
print(numpoly.cross_truncate(numpy.array([[5,1,1,1]]), 8, 1.0))       # True
print(numpoly.cross_truncate(numpy.array([[5,1,1,1,1]]), 9, 1.0))     # False
print(numpoly.cross_truncate(numpy.array([[5,1,1,1,1,1]]), 10, 1.0))  # True
```
This is interesting, I'll take a close look.

**Comment by JeremyDubut** [comment]
Ah, my bad. I messed my example because I am calling cross_truncate using glexindex which uses a '-1'.
I played a bit with it, and the behaviour is very surprising, and several indices are truncated in the case where the bound is 9.

**Comment by jonathf** [comment]
No problem.

So the problem relates to rounding error, created by division as you hinted to.

I think the best course of action is to add a nudge factor to acount for this kind of error, as a reformulation will be difficult to do and still cover all usecases. I think a small nudge factor will easily both bit enough to cover the rounding error issue, but also be small enough for the user not to notice.

I've made a proposed solution which, until I release, you can try out here:

    pip install git+https://github.com/jonathf/numpoly.git@trunc_threshold

You noted there were several such indices.
Do you mind either trying out the proposed solution yourself, or letting me know what the problem cases are so I can take a look?

**Comment by JeremyDubut** [comment]
I understand your issue, and probably your patch is enough for now.

I will not have time to make more tests in the coming days, but here are other indices that seemed problematic (still with bound 9 and norm 1) because not generated by glexindex:
- any permutation of the previous indices and of the following ones,
- [4,1,1,1,1,1]
- [3,2,1,1,1,1].

I have a sufficiently stable version of my code right now, so I will integrate your patch after you release it, and when I will have more time.

By the way, thank you for this library, it is quite useful :-)

**Comment by jonathf** [comment]
Okay, thanks. I've checked them and a did a small search in 5-D, and it looks like it works as expected now. Looks like a nudge of `1e-15` is enough, but for safty, I've set it to `1e-12*dim`. Should be enough.

Feature added to release v1.1.4.
